---
title: design-project-template
hero_image: images/banner.png
description: design-project-template description
version: 5
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
- title: What you will make
- title: Step title
- title: Step title
- title: Step title
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Challenge
  challenge: true
- title: What can you do now?
